// Importa a função `localFont` do Next.js para carregar fontes locais
import localFont from "next/font/local";

// Importa o arquivo global de estilos CSS
import "./globals.css";

// Define uma fonte chamada "geistSans" usando a função `localFont`
// O arquivo de fonte é especificado por seu caminho relativo ("./fonts/GeistVF.woff")
// A variável CSS que será criada para essa fonte é '--font-geist-sans', e ela irá abranger pesos de 100 a 900
const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Caminho para o arquivo de fonte
  variable: "--font-geist-sans", // Nome da variável CSS que armazenará a fonte
  weight: "100 900", // Intervalo de pesos disponíveis para essa fonte
});

// Define uma segunda fonte chamada "geistMono" de maneira semelhante à primeira
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", 
  variable: "--font-geist-mono", 
  weight: "100 900", 
});

// Define o objeto `metadata`, que contém as informações básicas sobre o site
export const metadata = {
  title: "Create Next App", // Título da página (aparece na aba do navegador)
  description: "Generated by create next app", // Descrição do site
};

// Função que representa o layout raiz da aplicação, que envolve todos os componentes da aplicação
// Aplica as fontes "geistSans" e "geistMono" no corpo da página
// As variáveis CSS definidas anteriormente são usadas aqui
// A classe `antialiased` melhora a renderização das fontes, deixando-as mais suaves
/* Renderiza os filhos da página (conteúdo dinâmico da aplicação) */ 
/* Define o idioma da página como português do Brasil */ 
export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
